#                                     Week3 - 복습과제

## 문제1.

### 문제 1-1.
#### bmi = 체중(kg) / 신장(m)²입니다. 이 공식을 바탕으로 체중을 계산하여 새로운 열(weight)로 추가한 후 소수점 아래 첫째 자리까지 반올림한 후 상위 10개 데이터를 출력해주세요.
#### 힌트 1) 데이터 속의 신장은 cm 단위이지만 bmi를 계산하기 위해서는 m 단위의 신장이 필요합니다.             
#### 힌트 2) 파이썬은 x의 y제곱을 x**y로 나타낼 수 있습니다.


In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('insurance.csv')

In [4]:
df['height']=df['height']/100

In [6]:
df['weight']=df['bmi']*(df['height']**2)

### 문제 1-2.
#### 체중을 5개의 구간으로 나눈 후 각 구간의 경계값을 출력해주세요. 또 각 경계값에 '완전 과체중, 과체중, 보통체중, 저체중, 과한 저체중' 다섯 개의 이름으로 저장한 후 체중과 경계값의 첫 15개 행을 함께 출력해주세요.

In [10]:
count, bin_dividers=np.histogram(df['weight'], bins=5)
bin_names=['완전과체중','과체중','보통체중','저체중','과한저체중']
df['weight_bin']=pd.cut(x=df['weight'], bins=bin_dividers,labels=bin_names, include_lowest=True)
df[['weight', 'weight_bin']].head(15)

weight weight_bin
0    70.533990        과체중
1   106.996868       보통체중
2   111.724800       보통체중
3    73.564200        과체중
4    88.445000        과체중
5    71.786286        과체중
6    67.428416      완전과체중
7    64.090496      완전과체중
8    93.454407        과체중
9    59.700736      완전과체중
10   80.298750        과체중
11   73.320181        과체중
12  111.456000       보통체중
13   82.570752        과체중
14  153.694453        저체중

## 문제2.

### 문제 2-1.
#### insurance.csv파일 내 숫자형 데이터 피처의 평균과 분산을 확인하고 표준화를 진행해주세요! 
#### 표준화된 데이터 피처의 평균과 분산을 결과값으로 출력해주세요! StandardScaler를 활용해주세요! 1번에서 사용하신 df를 그대로 사용하시면 됩니다!

In [17]:
from sklearn.preprocessing import StandardScaler

In [39]:
ndf=df.drop(['sex', 'smoker','region', 'weight_bin'], axis=1)

In [47]:
scaler=StandardScaler()
scaler.fit(ndf)
ndf_scaled=scaler.transform(ndf)
ndf_scaled=pd.DataFrame(data=ndf_scaled)
ndf_sclaed.mean()
ndf_scaled.var()

0    1.000748
1    1.000748
2    1.000748
3    1.000748
4    1.000748
5    1.000748
dtype: float64

### 문제 2-2.
#### insurance.csv파일 내 숫자형 데이터 피처의 정규화를 지시에 따라 진행해주세요! 정규화된 데이터 피처의 최댓값과 최솟값을 결과값으로 출력해주세요

#### 2-2-1.
#### MinMaxScaler로 정규화 작업을 진행해주세요

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [59]:
scaler=MinMaxScaler()
scaler.fit(ndf)
ndf_scaled=scaler.transform(ndf)
ndf_scaled=pd.DataFrame(data=ndf_scaled)
ndf_scaled.max()
ndf_scaled.min()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
dtype: float64

#### 문제 2-2-2.
##### 각 열의 최댓값의 절대값으로 각 열 데이터를 나눠주는 방법으로 정규화 작업을 진행해주세요!

In [61]:
ndf_abs_scaled=ndf/abs(ndf.max())
ndf_abs_scaled.max()
ndf_abs_scaled.min()

age         0.281250
bmi         0.300395
height      0.729167
children    0.000000
charges     0.017592
weight      0.190094
dtype: float64

#### 문제2-2-3.
##### 벡터 정규화를 진행해주세요! 정규화된 데이터 프레임의 Norm을 추가로 출력해주세요!

In [63]:
an_array=np.random.rand(10)*10
norm=np.linalg.norm(an_array)
normal_array=an_array/norm

In [65]:
ndf_vector_scaled=ndf/np.linalg.norm(ndf)
ndf_vector_scaled.max()
ndf_vector_scaled.min()

age         0.000027
bmi         0.000024
height      0.000002
children    0.000000
charges     0.001707
weight      0.000057
dtype: float64

## 문제3.

### 문제 3-1.
#### credit.csv 파일을 dataframe으로 읽은 후, unknown 값을 NaN으로 바꿔주세요.

In [66]:
import pandas as pd
import numpy as np

df = pd.read_csv('credit.csv')

In [68]:
df.replace('unknown', np.nan, inplace=True)

### 문제 3-2.
#### 각 column의 누락 데이터 수를 확인(try & except문) 한 후에, checking_balance 누락 값은 해당 열에서 가장 많이 나타나는 값으로 바꾸고, savings_balance 누락 값은 이웃하고 있는 바로 다음 행 값으로 바꾼다.

In [75]:
missing_df=df.isnull()
for col in missing_df.columns:
    missing_count=missing_df[col].value_counts()
    
    try:
        print(col, ':', missing_count[True])
    except:
        print(col, ':', 0)

In [74]:
most_freq=df['checking_balance'].value_counts(dropna=True).idxmax()
df['checking_balance'].fillna(most_freq, inplace=True)
df['savings_balance'].fillna(method='bfill', inplace=True)

## 문제4.
### credit데이터를 불러와서 원-핫인코딩하기



### 4-1. credit 데이터의 'credit_history'피처를 사이킷런의 머신러닝알고리즘을 통해 인코딩해보세요


#### 4-1-1. 먼저, 숫자값으로의 변환을 위해 레이블인코딩하기

* credit_data에 파일을 불러온 뒤 credit_data1에 'credit_history'피처만 저장 후 인코딩
* 어떤 데이터가 어떻게 인코딩되었는지 나타내기(classes_ 사용하세요)
* 변환된 데이터 값 출력

In [90]:
from sklearn.preprocessing import LabelEncoder
df=pd.read_csv('credit.csv')

In [117]:
df['credit_history']=df['credit_history'].astype('category')
credit_data1=list(df['credit_history'].unique())

In [126]:
encoder=LabelEncoder()
encoder.fit(credit_data1)
labels=encoder.transform(credit_data1)
print(credit_data1)
print(encoder.classes_)
print('인코딩 변환값:', labels)

['critical', 'good', 'poor', 'perfect', 'very good']
['critical' 'good' 'perfect' 'poor' 'very good']
인코딩 변환값: [0 1 3 2 4]


#### 4-1-2. 원핫인코딩 하기

* 변환된 데이터값 출력
* 원본데이터가 몇 행 몇 열의 데이터로 변환되었는지 나타내기

In [157]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
credit_data = data=pd.read_csv('./credit.csv')
encoder=LabelEncoder()
encoder.fit(credit_data1)
labels=encoder.transform(credit_data1)
labels=labels.reshape(-1,1)
labels

array([[0],
       [1],
       [3],
       [2],
       [4]], dtype=int64)

In [161]:
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


### 4-2. credit 데이터의 'default'피처를 판다스 API를 통해 인코딩해보세요

In [172]:
df=pd.read_csv('credit.csv')
df=pd.DataFrame(df['default'])
pd.get_dummies(df)

default_no  default_yes
0             1            0
1             0            1
2             1            0
3             1            0
4             0            1
..          ...          ...
995           1            0
996           1            0
997           1            0
998           0            1
999           1            0

[1000 rows x 2 columns]