In [100]:
import seaborn as sns
df=sns.load_dataset('titanic')
df.head()
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [102]:
nan_deck=df['deck'].value_counts(dropna=False) #dropna=False : nan값을 구할 수 있음
nan_deck

NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: deck, dtype: int64

In [103]:
df.head().isnull()

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0     False   False  False  False  False  False  False     False  False   
1     False   False  False  False  False  False  False     False  False   
2     False   False  False  False  False  False  False     False  False   
3     False   False  False  False  False  False  False     False  False   
4     False   False  False  False  False  False  False     False  False   

     who  adult_male   deck  embark_town  alive  alone  
0  False       False   True        False  False  False  
1  False       False  False        False  False  False  
2  False       False   True        False  False  False  
3  False       False  False        False  False  False  
4  False       False   True        False  False  False

In [104]:
df.head().notnull()

survived  pclass   sex   age  sibsp  parch  fare  embarked  class   who  \
0      True    True  True  True   True   True  True      True   True  True   
1      True    True  True  True   True   True  True      True   True  True   
2      True    True  True  True   True   True  True      True   True  True   
3      True    True  True  True   True   True  True      True   True  True   
4      True    True  True  True   True   True  True      True   True  True   

   adult_male   deck  embark_town  alive  alone  
0        True  False         True   True   True  
1        True   True         True   True   True  
2        True  False         True   True   True  
3        True   True         True   True   True  
4        True  False         True   True   True

In [105]:
df.head().isnull().sum(axis=0) #axis=0 : 행을 더하기

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           3
embark_town    0
alive          0
alone          0
dtype: int64

In [106]:
df.head().isnull().sum(axis=1)

0    1
1    0
2    1
3    0
4    1
dtype: int64

In [107]:
import seaborn as sns
df=sns.load_dataset('titanic')
missing_df=df.isnull()
for col in missing_df.columns:
    missing_count=missing_df[col].value_counts()   
    try:
        print(col, ';', missing_count[True])
    except:
        print(col, ':', 0)

survived : 0
pclass : 0
sex : 0
age ; 177
sibsp : 0
parch : 0
fare : 0
embarked ; 2
class : 0
who : 0
adult_male : 0
deck ; 688
embark_town ; 2
alive : 0
alone : 0


In [108]:
df_thresh=df.dropna(thresh=500, axis=1)
df_thresh.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [109]:
df_thresh

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male  embark_town alive  alone  
0      man        True  Southampton    no  False  
1    woman       False    Cherbourg   yes  False  
2    woman       False  Southampton   yes   True  
3    woman       False  Southampton   yes  False  
4      man        True  Southampton    no   True  
..     ...         ...          ...   ...    ...  
886    man        True  Southampton    no   True  
887  woman       False  Southampton   yes   True  
888  woman       False  Southampton    no  False  
889    man        True    Cherbourg   yes   True  
890    man        True   Queenstown    no   True  

[891 rows x 14 columns]

In [110]:
df_age=df.dropna(axis=0, subset=['age'], how='any')
df_age

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
885         0       3  female  39.0      0      5  29.1250        Q   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
885  woman       False  NaN   Queenstown    no  False  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[714 rows x 15 columns]

In [111]:
df=sns.load_dataset('titanic')

In [112]:
mean_age=df['age'].mean(axis=0)
df['age'].fillna(mean_age, inplace=True)
df['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [113]:
import numpy as np
import pandas as pd

df_ex=pd.DataFrame([[np.nan, 1, 3], [5, np.nan, 4], [8,6,np.nan]], columns=('A','B','C'))
df_ex

A    B    C
0  NaN  1.0  3.0
1  5.0  NaN  4.0
2  8.0  6.0  NaN

In [114]:
df_ex['A']
median_ex=df_ex['A'].median(axis=0)
df_ex['A'].fillna(median_ex, inplace=True)
df_ex

A    B    C
0  6.5  1.0  3.0
1  5.0  NaN  4.0
2  8.0  6.0  NaN

In [115]:
values={'B':0, 'C':9}
df_ex.fillna(value=values, inplace=True)
df_ex

A    B    C
0  6.5  1.0  3.0
1  5.0  0.0  4.0
2  8.0  6.0  9.0

In [116]:
most_freq=df['embark_town'].value_counts(dropna=True).idxmax()
df['embark_town'].fillna(most_freq, inplace=True)
df['embark_town'][825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829    Southampton
Name: embark_town, dtype: object

In [117]:
df=sns.load_dataset('titanic')
df['embark_town'].fillna(method='ffill', inplace=True)
df['embark_town'][825:830]

825     Queenstown
826    Southampton
827      Cherbourg
828     Queenstown
829     Queenstown
Name: embark_town, dtype: object

In [118]:
import pandas as pd
df=pd.DataFrame({'c1':['a','a','b','a','b'], 'c2':[1,1,1,2,2], 'c3':[1,1,2,2,2]})
df_dup=df.duplicated()


In [119]:
col_dup=df['c2'].duplicated()
col_dup

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [120]:
df2=df.drop_duplicates()
df2

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [121]:
df3=df.drop_duplicates(subset=['c2','c3'])
df3

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2

In [122]:
import pandas as pd
df=pd.read_csv('auto-mpg.csv', header=None)
df.columns=['mpg','cylinders','displacement','horsepower','weight','accerlation','model year','origin','name' ]

In [123]:
df

mpg  cylinders  displacement horsepower  weight  accerlation  \
0    18.0          8         307.0      130.0  3504.0         12.0   
1    15.0          8         350.0      165.0  3693.0         11.5   
2    18.0          8         318.0      150.0  3436.0         11.0   
3    16.0          8         304.0      150.0  3433.0         12.0   
4    17.0          8         302.0      140.0  3449.0         10.5   
..    ...        ...           ...        ...     ...          ...   
393  27.0          4         140.0      86.00  2790.0         15.6   
394  44.0          4          97.0      52.00  2130.0         24.6   
395  32.0          4         135.0      84.00  2295.0         11.6   
396  28.0          4         120.0      79.00  2625.0         18.6   
397  31.0          4         119.0      82.00  2720.0         19.4   

     model year  origin                       name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [124]:
mpg_to_kpl=1.60934/3.78541
df['kpl']=df['mpg']*mpg_to_kpl
df

mpg  cylinders  displacement horsepower  weight  accerlation  \
0    18.0          8         307.0      130.0  3504.0         12.0   
1    15.0          8         350.0      165.0  3693.0         11.5   
2    18.0          8         318.0      150.0  3436.0         11.0   
3    16.0          8         304.0      150.0  3433.0         12.0   
4    17.0          8         302.0      140.0  3449.0         10.5   
..    ...        ...           ...        ...     ...          ...   
393  27.0          4         140.0      86.00  2790.0         15.6   
394  44.0          4          97.0      52.00  2130.0         24.6   
395  32.0          4         135.0      84.00  2295.0         11.6   
396  28.0          4         120.0      79.00  2625.0         18.6   
397  31.0          4         119.0      82.00  2720.0         19.4   

     model year  origin                       name        kpl  
0            70       1  chevrolet chevelle malibu   7.652571  
1            70       1          buick skylark 320   6.377143  
2            70       1         plymouth satellite   7.652571  
3            70       1              amc rebel sst   6.802286  
4            70       1                ford torino   7.227428  
..          ...     ...                        ...        ...  
393          82       1            ford mustang gl  11.478857  
394          82       2                  vw pickup  18.706285  
395          82       1              dodge rampage  13.604571  
396          82       1                ford ranger  11.904000  
397          82       1                 chevy s-10  13.179428  

[398 rows x 10 columns]

In [125]:
df['kpl']=df['kpl'].round(2)
df

mpg  cylinders  displacement horsepower  weight  accerlation  \
0    18.0          8         307.0      130.0  3504.0         12.0   
1    15.0          8         350.0      165.0  3693.0         11.5   
2    18.0          8         318.0      150.0  3436.0         11.0   
3    16.0          8         304.0      150.0  3433.0         12.0   
4    17.0          8         302.0      140.0  3449.0         10.5   
..    ...        ...           ...        ...     ...          ...   
393  27.0          4         140.0      86.00  2790.0         15.6   
394  44.0          4          97.0      52.00  2130.0         24.6   
395  32.0          4         135.0      84.00  2295.0         11.6   
396  28.0          4         120.0      79.00  2625.0         18.6   
397  31.0          4         119.0      82.00  2720.0         19.4   

     model year  origin                       name    kpl  
0            70       1  chevrolet chevelle malibu   7.65  
1            70       1          buick skylark 320   6.38  
2            70       1         plymouth satellite   7.65  
3            70       1              amc rebel sst   6.80  
4            70       1                ford torino   7.23  
..          ...     ...                        ...    ...  
393          82       1            ford mustang gl  11.48  
394          82       2                  vw pickup  18.71  
395          82       1              dodge rampage  13.60  
396          82       1                ford ranger  11.90  
397          82       1                 chevy s-10  13.18  

[398 rows x 10 columns]

In [126]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
accerlation     float64
model year        int64
origin            int64
name             object
kpl             float64
dtype: object

In [127]:
df['horsepower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [128]:
df['horsepower'].replace('?',np.nan, inplace=True)
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower']=df['horsepower'].astype('float')
df['horsepower'].dtype

dtype('float64')

In [129]:
df['origin'].unique()

array([1, 3, 2], dtype=int64)

In [130]:
df['origin'].replace({1:'USA', 2:'EU', 3:'JPN'}, inplace=True)
df['origin'].unique()
df['origin'].dtype

dtype('O')

In [131]:
df['origin'].unique()

array(['USA', 'JPN', 'EU'], dtype=object)

In [132]:
df['origin']=df['origin'].astype('category')
df['origin'].dtypes

CategoricalDtype(categories=['EU', 'JPN', 'USA'], ordered=False)

In [133]:
df['origin']=df['origin'].astype('str')
df['origin'].dtype

dtype('O')

In [134]:
df['model year'].sample(3)

388    82
174    75
53     71
Name: model year, dtype: int64

In [135]:
df['model year']=df['model year'].astype('category')
df['model year'].sample(3)

317    80
19     70
239    77
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

In [136]:
count, bin_dividers=np.histogram(df['horsepower'], bins=3)

In [137]:
bin_names=['저출력','보통출력','고출력']
df['hp_bin']=pd.cut(x=df['horsepower'], bins=bin_dividers, labels=bin_names)

In [138]:
df['hp_bin'].head(15)

0     보통출력
1     보통출력
2     보통출력
3     보통출력
4     보통출력
5      고출력
6      고출력
7      고출력
8      고출력
9      고출력
10     고출력
11    보통출력
12    보통출력
13     고출력
14     저출력
Name: hp_bin, dtype: category
Categories (3, object): [저출력 < 보통출력 < 고출력]

In [152]:
from sklearn.preprocessing import LabelEncoder

In [153]:
from sklearn.preprocessing import OneHotEncoder

In [140]:
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [141]:
encoder=LabelEncoder()

In [142]:
encoder.fit(items)

LabelEncoder()

In [143]:
labels=encoder.transform(items)

In [144]:
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [145]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [146]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [150]:
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
labels=labels.reshape(-1,1)

In [155]:
oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [158]:
df=pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [160]:
from sklearn.datasets import load_iris
import pandas as pd
iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
print('<데이터의 평균 값>')
print(iris_df.mean())
print('\n<데이터의 분산 값>')
print(iris_df.var())
iris_df.head()

<데이터의 평균 값>
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

<데이터의 분산 값>
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [162]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_df_scaled=pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('<데이터의 평균 값>')
print(iris_df_scaled.mean())
print('\n<데이터의 분산 값>')
print(iris_df_scaled.var())

<데이터의 평균 값>
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

<데이터의 분산 값>
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [167]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_df_scaled=pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('<정규화된 데이터의 최댓값>')
print(iris_df_scaled.max())
print('\n<정규화된 데이터의 최솟값>')
print(iris_df_scaled.min())

<정규화된 데이터의 최댓값>
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

<정규화된 데이터의 최솟값>
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64


In [168]:
iris_df_abs_scaled=iris_df/abs(iris_df.max())
print('<abs 정규화된 데이터의 최댓값>')
print(iris_df_abs_scaled.max())
print('\n<abs 정규화된 데이터의 최솟값>')
print(iris_df_abs_scaled.min())

<abs 정규화된 데이터의 최댓값>
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

<abs 정규화된 데이터의 최솟값>
sepal length (cm)    0.544304
sepal width (cm)     0.454545
petal length (cm)    0.144928
petal width (cm)     0.040000
dtype: float64


In [172]:
an_array=np.random.rand(10)*10
print('<원 배열>\n, an_array')
norm=np.linalg.norm(an_array)
print('<원 배열의 Norm> \n', norm)
normal_array=an_array/norm
print('<벡터정규화된 배열>\n', normal_array)
print('<벡터정규화된 배열의 Norm>', np.linalg.norm(normal_array))

<원 배열>
, an_array
<원 배열의 Norm> 
 17.329224784762733
<벡터정규화된 배열>
 [0.36105248 0.38719284 0.20849004 0.1462846  0.19135725 0.24273355
 0.2309761  0.00895728 0.42553097 0.56992241]
<벡터정규화된 배열의 Norm> 1.0


In [174]:
iris_df_vector_scaled=iris_df/np.linalg.norm(iris_df)
print("<벡터 정규화된 데이터의 최댓값>")
print(iris_df_vector_scaled.max())
print("<벡터 정규화된 데이터의 최솟값>")
print("<원 데이터 프레임의 Norm>", np.linalg.norm(iris_df))
print("<벡터 정규화된 데이터 프레임의 Norm>", np.linalg.norm(iris_df_vector_scaled))

<벡터 정규화된 데이터의 최댓값>
sepal length (cm)    0.080885
sepal width (cm)     0.045050
petal length (cm)    0.070647
petal width (cm)     0.025597
dtype: float64
<벡터 정규화된 데이터의 최솟값>
<원 데이터 프레임의 Norm> 97.66928892952994
<벡터 정규화된 데이터 프레임의 Norm> 1.0


In [176]:
train_array=np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,6).reshape(-1,1)

In [177]:
scaler=MinMaxScaler()

In [178]:
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)

In [179]:
print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [180]:
scaler.fit(test_array)
test_scaled=scaler.transform(test_array)
print('원본 test_array 데이터:', np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]


In [181]:
test_scaled=scaler.transform(test_array)
print('\n원본 test_away 데이터:', np.round(test_array.reshape(-1),2))
print('Scale된 test_array 데이터:', np.round(test_scaled.reshape(-1),2))


원본 test_away 데이터: [0 1 2 3 4 5]
Scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]
